FROM ghcr.io/puppeteer/puppeteer:21.6.1

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

WORKDIR /app

COPY package*.json ./
ENV ONNXRUNTIME_NODE_INSTALL=skip
RUN npm ci --omit=dev

COPY . .

EXPOSE 3000

CMD ["node", "index.js"]